name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint-cli:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: .
          config_file: ".markdownlint.yaml"

  yamllint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run YAML Lint
        uses: actionshub/yamllint@main

  test:
    needs: [markdownlint-cli, yamllint]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java-version }}
    strategy:
      matrix:
        java-version:
          - '11'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL_DEVELOPMENT}}
